name: plan_lekcji
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  html: ^0.15.3
  http: ^0.13.6
  shared_preferences: ^2.1.1
  go_router: ^7.0.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  image_path: "assets/logo.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/elektronik.jpg
    - assets/logo.jpg