import '../models/teacher_data.dart';

List<TeacherData> teacherData = [
  TeacherData(simple: 'KW', full: 'K.WITKOWSKI'),
  TeacherData(simple: 'PA', full: 'A.PAŹDZIOR'),
  TeacherData(simple: 'ST', full: 'S.SYTA'),
  TeacherData(simple: 'ZM', full: 'Z.MATYGA'),
  TeacherData(simple: 'RF', full: 'R.FIGURA'),
  TeacherData(simple: 'AM', full: 'M.ADAMCZYK'),
  TeacherData(simple: 'BB', full: 'B.BAKINOWSKA-MARCHEWKA'),
  TeacherData(simple: 'DB', full: 'D.BANACH'),
  TeacherData(simple: 'GB', full: 'G.BARSZCZ'),
  TeacherData(simple: 'BZ', full: 'K.BAŻYNSKI'),
  TeacherData(simple: 'AD', full: 'A.BESTER'),
  TeacherData(simple: 'CH', full: 'M.CHRZAN'),
  TeacherData(simple: 'CZ', full: 'B.CHRZĄSZCZ'),
  TeacherData(simple: 'LI', full: 'M.CICHAWA'),
  TeacherData(simple: 'CR', full: 'B.CZERSKA'),
  TeacherData(simple: 'CW', full: 'K.CWAJDA'),
  TeacherData(simple: 'JC', full: 'J.CZYŻ'),
  TeacherData(simple: 'DY', full: 'M.DYGAŁA'),
  TeacherData(simple: 'BG', full: 'B.GRADZIK'),
  TeacherData(simple: 'DA', full: 'K.DASIEWICZ'),
  TeacherData(simple: 'AG', full: 'A.GREGOREK'),
  TeacherData(simple: 'JK', full: 'J.KALBARCZYK'),
  TeacherData(simple: 'ZD', full: 'Z.DOBKIEWICZ'),
  TeacherData(simple: 'XK', full: 'A.KALITA'),
  TeacherData(simple: 'KM', full: 'M.KALITA'),
  TeacherData(simple: 'KP', full: 'K.KAPECKA'),
  TeacherData(simple: 'KĘ', full: 'K.KĘSKA'),
  TeacherData(simple: 'KJ', full: 'J.KIEŁBIOWSKI'),
  TeacherData(simple: 'IK', full: 'I.KOŁDEJ'),
  TeacherData(simple: 'RJ', full: 'R.JUSZKIEWICZ'),
  TeacherData(simple: 'BK', full: 'B.KOSTKIEWICZ'),
  TeacherData(simple: 'KI', full: 'I.KOWALCZYK'),
  TeacherData(simple: 'KK', full: 'M.KOWALCZYK'),
  TeacherData(simple: 'KC', full: 'K.KOZIEŁ'),
  TeacherData(simple: 'MR', full: 'M.KOZŁOWSKI'),
  TeacherData(simple: 'KO', full: 'P.KOZŁOWSKI'),
  TeacherData(simple: 'KZ', full: 'J.KOZUŃ'),
  TeacherData(simple: 'GT', full: 'K.KOGUT'),
  TeacherData(simple: 'EK', full: 'E.KRAWCZYK'),
  TeacherData(simple: 'KR', full: 'M.KUSIAK'),
  TeacherData(simple: 'MK', full: 'M.KWIECIEŃ'),
  TeacherData(simple: 'IG', full: 'I.LINOWSKA'),
  TeacherData(simple: 'RA', full: 'R.KULAK'),
  TeacherData(simple: 'JL', full: 'J.ŁYJAK'),
  TeacherData(simple: 'MY', full: 'M.MAKOWSKI'),
  TeacherData(simple: 'MM', full: 'M.MAMCZARZ'),
  TeacherData(simple: 'TM', full: 'T.MAREK'),
  TeacherData(simple: 'JM', full: 'J.MARSZAŁEK'),
  TeacherData(simple: 'ME', full: 'E.MIŁKOWSKA'),
  TeacherData(simple: 'EM', full: 'E.MITAK'),
  TeacherData(simple: 'MP', full: 'M.NAGRODZKA'),
  TeacherData(simple: 'AN', full: 'A.NOWOCIEŃ'),
  TeacherData(simple: 'MI', full: 'M.MIGUS'),
  TeacherData(simple: 'OD', full: 'D.OKÓLSKA'),
  TeacherData(simple: 'OR', full: 'R.OKRUTNY'),
  TeacherData(simple: 'RO', full: 'J.OLAS'),
  TeacherData(simple: 'AO', full: 'A.OLSZEWSKA-ZAPŁATA'),
  TeacherData(simple: 'PM', full: 'M.PASTUSIAK'),
  TeacherData(simple: 'OM', full: 'M.MORTKA'),
  TeacherData(simple: 'UP', full: 'U.PIETRZAK'),
  TeacherData(simple: 'TK', full: 'M.PIWOWARCZYK'),
  TeacherData(simple: 'RU', full: 'K.PŁOKITA'),
  TeacherData(simple: 'WP', full: 'W.POPIELARSKI'),
  TeacherData(simple: 'PU', full: 'K.PUCHALSKA'),
  TeacherData(simple: 'JR', full: 'J.ROŻEK'),
  TeacherData(simple: 'RL', full: 'Ł.RYLSKI'),
  TeacherData(simple: 'DS', full: 'D.SAJAK'),
  TeacherData(simple: 'PN', full: 'S.PIJANOWSKI'),
  TeacherData(simple: 'SE', full: 'K.SKÓRKIEWICZ'),
  TeacherData(simple: 'AB', full: 'A.SMOLARCZYK'),
  TeacherData(simple: 'SS', full: 'S.SOKOŁOWSKI'),
  TeacherData(simple: 'RP', full: 'R.PODSIADŁO'),
  TeacherData(simple: 'SO', full: 'K.SOLECKA'),
  TeacherData(simple: 'KS', full: 'K.SOLECKA-CIELOCH'),
  TeacherData(simple: 'SN', full: 'M.STAŃCZYK'),
  TeacherData(simple: 'JS', full: 'J.STĘPIEŃ'),
  TeacherData(simple: 'MO', full: 'M.STĘPIEŃ'),
  TeacherData(simple: 'SZ', full: 'S.SZAFRANOWICZ'),
  TeacherData(simple: 'SC', full: 'M.SZCZEPANOWSKI'),
  TeacherData(simple: 'SG', full: 'M.SZCZEPAŃSKA'),
  TeacherData(simple: 'DT', full: 'D.TOMASZEWSKA'),
  TeacherData(simple: 'PW', full: 'P.WACH'),
  TeacherData(simple: 'DW', full: 'D.WĘGRZYCKA'),
  TeacherData(simple: 'WE', full: 'M.WESELSKI'),
  TeacherData(simple: 'GA', full: 'A.WIECZOREK'),
  TeacherData(simple: 'WW', full: 'W.WIŚNIEWSKI'),
  TeacherData(simple: 'PS', full: 'P.STODULSKI'),
  TeacherData(simple: 'WH', full: 'W.WOJCIECHOWSKI'),
  TeacherData(simple: 'AW', full: 'A.WOJTAN'),
  TeacherData(simple: 'ZW', full: 'Z.WOSION'),
  TeacherData(simple: 'SM', full: 'M.WYSZYŃSKA'),
  TeacherData(simple: 'PZ', full: 'P.ZARĘBSKI'),
  TeacherData(simple: 'SY', full: 'M.SZYKOWNY'),
  TeacherData(simple: 'ZK', full: 'K.ZIELEZIŃSKA'),
  TeacherData(simple: 'ZG', full: 'M.ZWIERZCHOWSKA'),
  TeacherData(simple: 'SX', full: 'M.SULIGOWSKA'),
  TeacherData(simple: 'IT', full: 'I.TATARYN'),
  TeacherData(simple: 'EZ', full: 'E.ZIELIŃSKA'),
  TeacherData(simple: 'HZ', full: 'H.ŻUKOWSKA'),
];

List<String> weekdays = [
  "Poniedziałek",
  "Wtorek",
  "Środa",
  "Czwartek",
  "Piątek",
  "Sobota",
  "Niedziela",
];
